### ISSUE TITLE
那个。。报个bug

### ISSUE THREAD

**Issue by zhenruyan** [newday-me/think-cms#2]
上传设置后url无效，无论怎么设置都是www.domain.com 已清理缓存之类的

**Comment by newday-me** [comment]
我本地将上传驱动改为又拍云，然后修改了又拍云配置，测试上传正常。
你可以具体描述一下，比如你是选择了什么上传方式，然后对应的配置大概是怎样的呢？

**Comment by zhenruyan** [comment]
上传驱动为本地。改的host  test22.com -> 127.0.0.1  然后在上传驱动里改www.domain.com为test22.com/但是上传文件返回的url还是www.domain.com/  还有百度ueditr 我加上那个视频上传， 测试返回的路径也是这样的问题

**Comment by newday-me** [comment]
我将上传驱动改为本地，配置改为如下，测试没问题。
`
{
  "root": "{WEB_PATH}",
  "dir": "upload/",
  "base_url": "http://dev.newday.com/"
}
`
百度编辑器的上传用的都是全局上传对象，所以结果是一样的。

**Comment by karllo** [comment]
我用的是xampp
浏览器输入：http://localhost:89/install.html
出现以下内容
Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.

Error 404

localhost
Apache/2.4.18 (Win32) PHP/5.6.16


进入系统的正确方法是什么？

**Comment by zhenruyan** [comment]
说实在的。。。需要修改httpd的配置文件。=。   我也想搞成php -S localhostt:xxxx  直接可以用的。。。。。
