### ISSUE TITLE
为什么无法安装数据库？

### ISSUE THREAD

**Issue by karllo** [newday-me/think-cms#3]
我用的是xampp
浏览器输入：http://localhost:89/install.html
出现以下内容
Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.

Error 404

localhost
Apache/2.4.18 (Win32) PHP/5.6.16

进入系统的正确方法是什么？

**Comment by newday-me** [comment]
httpd-vhosts.conf

`<VirtualHost *:80>`
`	ServerName www.domain.com`
`	DocumentRoot "C:/www/cms/public"`
`	<Directory "C:/www/cms/public">` 
`		Options FollowSymLinks ExecCGI`
`		DirectoryIndex index.html index.htm index.php`
`		AllowOverride all` 
`		Order Deny,Allow` 
`		Allow from all` 
`		Require all granted`
`	</Directory>`
`</VirtualHost>`

.htaccess
`
RewriteRule ^(.*)$ index.php/?s=$1 [QSA,PT,L]

如提示manage_editor不存在，请先删除该变量进行安装，安装完成后还原此变量。

**Comment by newday-me** [comment]
具体查看文档的 [安装教程](http://www.kancloud.cn/newday_me/think-cms/300146) 。
